openapi: "3.0.0"
info:
  version: 1.0.0
  title: Agave Projects
  license:
    name: MIT
servers:
  - url: https://local.flowforma.com/api/integrations/agave
paths:
  /projects:
    get:
      summary: List all projects
      operationId: listProjects
      tags:
        - projects
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of projects
          headers:
            x-flowforma-agaveaccounttokenid:
              description: A agave account token id
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Project"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a project
      operationId: createProjects
      tags:
        - projects
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /projects/{projectId}:
    get:
      summary: Info for a specific project
      operationId: showProjectById
      tags:
        - project
      parameters:
        - name: projectId
          in: path
          required: true
          description: The id of the project to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Projects:
      type: array
      items:
        $ref: "#/components/schemas/Project"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string